Exercise 1:
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [1]:
import numpy as np

# Creating the NumPy array with numbers from 1 to 10
arr = np.arange(1, 11)

# Reshapping it to  the array to a 2x5 matrix
reshaped_arr = arr.reshape(2, 5) # two row and 5 coloumn

# Display the reshaped array
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Exercise 2:
Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [4]:
import numpy as np

# Creating a NumPy array with numbers from 1 to 20
arr = np.arange(1, 21)

# Extracting the  elements between the 5th and 15th index (inclusive of 5th, exclusive of 15th)
extracted_elements = arr[5:16]

# Displaying  the extracted elements
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


Exercise 3: 
Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [29]:
import pandas as pd

# Create series
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(f'the first series:\n',fruit_series)
# Add a new item to the series
fruit_series['pears'] = 4

# Display the updated series
print(f'The updated series:\n',fruit_series)


the first series:
 apples     3
bananas    2
oranges    1
dtype: int64
The updated series:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


Exercise 4:
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [20]:
# Data for the DataFrame
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Dave', 'Eva', 'Frank', 'Grace', 'Hannah', 'Irin', 'Jack'],
    'age': [23, 34, 45, 22, 29, 41, 35, 27, 31, 28],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      name  age gender
0    Alice   23      F
1      Bob   34      M
2  Charlie   45      M
3     Dave   22      M
4      Eva   29      F
5    Frank   41      M
6    Grace   35      F
7   Hannah   27      F
8     Irin   31      F
9     Jack   28      M


Exercise 5:
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [32]:
# Data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Dave', 'Eva', 'Frank', 'Grace', 'Hannah', 'Irin', 'Jack'],
    'age': [23, 34, 45, 22, 29, 41, 35, 27, 31, 28],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

# Create the DataFrame
df = pd.DataFrame(data)
print(f'First dataframe:\n',df)

# Add the new 'occupation' column
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                     'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

print(f'The updated dataframe :\n',df)


First dataframe:
       name  age gender
0    Alice   23      F
1      Bob   34      M
2  Charlie   45      M
3     Dave   22      M
4      Eva   29      F
5    Frank   41      M
6    Grace   35      F
7   Hannah   27      F
8     Irin   31      F
9     Jack   28      M
The updated dataframe :
       name  age gender  occupation
0    Alice   23      F  Programmer
1      Bob   34      M     Manager
2  Charlie   45      M     Analyst
3     Dave   22      M  Programmer
4      Eva   29      F     Manager
5    Frank   41      M     Analyst
6    Grace   35      F  Programmer
7   Hannah   27      F     Manager
8     Irin   31      F     Analyst
9     Jack   28      M  Programmer


Exercise 6: 
Select the rows of the dataframe where the age is greater than or equal to 30.

In [34]:
# Create the DataFrame
df = pd.DataFrame(data) #using the perivous data

# Select rows where age is greater than or equal to 30
df_age_30_plus = df[df['age'] >= 30]

# Display the filtered DataFrame
print(df_age_30_plus)


      name  age gender
1      Bob   34      M
2  Charlie   45      M
5    Frank   41      M
6    Grace   35      F
8     Irin   31      F


Exercise 7:
Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [37]:

# Create the DataFrame
df = pd.DataFrame(data)

# Convert the DataFrame to a CSV file
df.to_csv('employee_data.csv', index=False)

# Read the CSV file back into a DataFrame
df_from_csv = pd.read_csv('employee_data.csv')

# Display the contents of the DataFrame
print(df_from_csv)


      name  age gender
0    Alice   23      F
1      Bob   34      M
2  Charlie   45      M
3     Dave   22      M
4      Eva   29      F
5    Frank   41      M
6    Grace   35      F
7   Hannah   27      F
8     Irin   31      F
9     Jack   28      M
